/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/product": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.product.id"];
          created_at?: parameters["rowFilter.product.created_at"];
          code?: parameters["rowFilter.product.code"];
          description?: parameters["rowFilter.product.description"];
          model?: parameters["rowFilter.product.model"];
          imgRef?: parameters["rowFilter.product.imgRef"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["product"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** product */
          product?: definitions["product"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.product.id"];
          created_at?: parameters["rowFilter.product.created_at"];
          code?: parameters["rowFilter.product.code"];
          description?: parameters["rowFilter.product.description"];
          model?: parameters["rowFilter.product.model"];
          imgRef?: parameters["rowFilter.product.imgRef"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.product.id"];
          created_at?: parameters["rowFilter.product.created_at"];
          code?: parameters["rowFilter.product.code"];
          description?: parameters["rowFilter.product.description"];
          model?: parameters["rowFilter.product.model"];
          imgRef?: parameters["rowFilter.product.imgRef"];
        };
        body: {
          /** product */
          product?: definitions["product"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  product: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: timestamp with time zone
     * @default (now() AT TIME ZONE 'utc'::text)
     */
    created_at?: string;
    /** Format: text */
    code: string;
    /** Format: text */
    description?: string;
    /** Format: text */
    model?: string;
    /** Format: text */
    imgRef?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description product */
  "body.product": definitions["product"];
  /** Format: uuid */
  "rowFilter.product.id": string;
  /** Format: timestamp with time zone */
  "rowFilter.product.created_at": string;
  /** Format: text */
  "rowFilter.product.code": string;
  /** Format: text */
  "rowFilter.product.description": string;
  /** Format: text */
  "rowFilter.product.model": string;
  /** Format: text */
  "rowFilter.product.imgRef": string;
}

export interface operations {}

export interface external {}
