-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.client
(
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    name text COLLATE pg_catalog."default",
    nit text COLLATE pg_catalog."default",
    CONSTRAINT client_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.client
    OWNER to postgres;

GRANT ALL ON TABLE public.client TO anon;

GRANT ALL ON TABLE public.client TO authenticated;

GRANT ALL ON TABLE public.client TO postgres;

GRANT ALL ON TABLE public.client TO service_role;

CREATE TABLE IF NOT EXISTS public.client_product
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    client uuid NOT NULL,
    product uuid NOT NULL,
    reference text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT client_product_pkey PRIMARY KEY (id),
    CONSTRAINT client_product_reference_key UNIQUE (reference),
    CONSTRAINT client_product_client_fkey FOREIGN KEY (client)
        REFERENCES public.client (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE cascade ,
    CONSTRAINT client_product_product_fkey FOREIGN KEY (product)
        REFERENCES public.product (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE cascade
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.client_product
    OWNER to postgres;

GRANT ALL ON TABLE public.client_product TO anon;

GRANT ALL ON TABLE public.client_product TO authenticated;

GRANT ALL ON TABLE public.client_product TO postgres;

GRANT ALL ON TABLE public.client_product TO service_role;
